# Generated by Django 4.1.6 on 2023-03-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id_orderdetail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(max_length=3)),
                ('id_equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.equipment')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
            ],
        ),
    ]
