# Generated by Django 4.1.6 on 2023-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('date_of_registration', models.DateField(verbose_name='Date of Registration')),
                ('image_account', models.BinaryField()),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('CU', 'Customer')], default='CU', max_length=2)),
            ],
        ),
    ]
