# Generated by Django 4.1.6 on 2023-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_equipment', models.AutoField(primary_key=True, serialize=False)),
                ('name_equipment', models.CharField(max_length=32)),
                ('price_equipment', models.DecimalField(decimal_places=3, max_digits=16)),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
