@startuml
actor       Customer    as 1
boundary    HomeView    as 2
control     System     as 3

1->2 : Chon dang xuat
activate 1
2->3 : Gui yeu cau dang xuat
activate 2
activate 3
3-->2 : return
deactivate 3
2-->1 : return
deactivate 2
deactivate 1

@enduml