@startuml
actor       Admin   as 1
boundary    ListOrderView    as 2
control     System     as 3
entity      PaymentClass     as 4


1->2 : Xem thong ke theo thang
activate 1
2->3 : Gui yeu cau
activate 2
3->4 : searchpayment()
4-->3 : return 
3-->2 : monthlyreport()
deactivate 3
2-->1 : return
deactivate 2
deactivate 1

@enduml