# Generated by Django 4.1.6 on 2023-03-14 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('footballpitchs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('ordered_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('WAI', 'Waiting'), ('CON', 'Confirmed')], default='WAI', max_length=64)),
                ('id_pitch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='footballpitchs.footballpitch')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account')),
            ],
        ),
    ]
